/// Generate the `api.ts` file content for a React UI project.
///
/// Produces a TenorClient class that implements all spec-defined executor
/// HTTP endpoints from Section 19.
pub(super) fn emit_api_client(api_url: &str, contract_id: &str) -> String {
    format!(
        r#"// Auto-generated by tenor ui. Do not edit.
// Executor API client for contract: {contract_id}

const API_BASE = '{api_url}';
const CONTRACT_ID = '{contract_id}';

export interface TenorManifest {{
  etag: string;
  contract_id: string;
  capabilities: string[];
  interchange: unknown;
}}

export interface FactSet {{
  [key: string]: unknown;
}}

export interface InstanceBindingMap {{
  [entityId: string]: string;
}}

export interface EntityInstance {{
  entity_id: string;
  instance_id: string;
  state: string;
}}

export interface EntityStateChange {{
  entity_id: string;
  from_state: string;
  to_state: string;
}}

export interface StepResult {{
  step_id: string;
  result: string;
}}

export interface Verdict {{
  verdict_type: string;
  payload: unknown;
  provenance: {{
    rule_id: string;
    stratum: number;
    facts_examined: string[];
  }};
}}

export interface FlowResult {{
  flow_id: string;
  outcome: string;
  simulation?: boolean;
  initiating_persona?: string;
  steps_executed: StepResult[];
  entity_state_changes: EntityStateChange[];
  verdicts: Verdict[];
}}

export interface ActionSpaceAction {{
  flow_id: string;
  available: boolean;
  reason?: string;
  enabling_verdicts?: string[];
  applicable_instances?: Record<string, string[]>;
}}

export interface ActionSpace {{
  persona: string;
  available: ActionSpaceAction[];
  blocked: ActionSpaceAction[];
}}

export interface FlowExecution {{
  execution_id: string;
  flow_id: string;
  persona: string;
  outcome: string;
  timestamp: string;
  entity_state_changes: EntityStateChange[];
}}

export class TenorClient {{
  private baseUrl: string;
  private contractId: string;

  constructor(baseUrl: string = API_BASE, contractId: string = CONTRACT_ID) {{
    this.baseUrl = baseUrl.replace(/\/$/, '');
    this.contractId = contractId;
  }}

  private async request<T>(path: string, options?: RequestInit): Promise<T> {{
    const url = `${{this.baseUrl}}${{path}}`;
    const res = await fetch(url, {{
      headers: {{ 'Content-Type': 'application/json', ...options?.headers }},
      ...options,
    }});
    if (!res.ok) {{
      const body = await res.text();
      throw new Error(`${{res.status}}: ${{body}}`);
    }}
    return res.json();
  }}

  async getManifest(): Promise<TenorManifest> {{
    return this.request<TenorManifest>(
      `/contracts/${{this.contractId}}/manifest`
    );
  }}

  async getActionSpace(persona: string, facts: FactSet): Promise<ActionSpace> {{
    return this.request<ActionSpace>(
      `/contracts/${{this.contractId}}/action-space`,
      {{
        method: 'POST',
        body: JSON.stringify({{ persona, facts }}),
      }}
    );
  }}

  async executeFlow(
    flowId: string,
    persona: string,
    facts: FactSet,
    instanceBindings: InstanceBindingMap
  ): Promise<FlowResult> {{
    return this.request<FlowResult>(
      `/contracts/${{this.contractId}}/flows/${{flowId}}/execute`,
      {{
        method: 'POST',
        body: JSON.stringify({{ persona, facts, instance_bindings: instanceBindings }}),
      }}
    );
  }}

  async simulateFlow(
    flowId: string,
    persona: string,
    facts: FactSet,
    instanceBindings: InstanceBindingMap
  ): Promise<FlowResult> {{
    return this.request<FlowResult>(
      `/contracts/${{this.contractId}}/flows/${{flowId}}/simulate`,
      {{
        method: 'POST',
        body: JSON.stringify({{ persona, facts, instance_bindings: instanceBindings }}),
      }}
    );
  }}

  async getEntityInstances(entityId: string): Promise<EntityInstance[]> {{
    return this.request<EntityInstance[]>(
      `/contracts/${{this.contractId}}/entities/${{entityId}}/instances`
    );
  }}

  async getEntityState(entityId: string, instanceId: string): Promise<string> {{
    return this.request<string>(
      `/contracts/${{this.contractId}}/entities/${{entityId}}/instances/${{instanceId}}/state`
    );
  }}

  async initializeEntity(entityId: string, instanceId: string): Promise<void> {{
    await this.request<void>(
      `/contracts/${{this.contractId}}/entities/${{entityId}}/instances/${{instanceId}}/initialize`,
      {{ method: 'POST' }}
    );
  }}

  async getExecutionHistory(): Promise<FlowExecution[]> {{
    return this.request<FlowExecution[]>(
      `/contracts/${{this.contractId}}/executions`
    );
  }}

  async getExecution(executionId: string): Promise<FlowExecution> {{
    return this.request<FlowExecution>(
      `/contracts/${{this.contractId}}/executions/${{executionId}}`
    );
  }}
}}

export const client = new TenorClient();
"#,
        contract_id = contract_id,
        api_url = api_url,
    )
}
