//! React component generation functions for the tenor UI project.
//!
//! Each function generates a complete TypeScript/React component file as a String.
//! Components use inline styles with theme variables and import from ../types, ../api, ../theme.

use tenor_codegen::bundle::CodegenBundle;
use tenor_codegen::typescript::to_pascal_case;

// ─────────────────────────────────────────────────────────────────────────────
// Dashboard and entity components (Task 3)
// ─────────────────────────────────────────────────────────────────────────────

/// Generate `Dashboard.tsx` content.
pub(super) fn emit_dashboard(bundle: &CodegenBundle) -> String {
    let entity_names: Vec<String> = bundle
        .entities
        .iter()
        .map(|e| to_pascal_case(&e.id))
        .collect();
    let entity_names_str = entity_names
        .iter()
        .map(|n| format!("    {{ id: '{}', label: '{}' }}", n, n))
        .collect::<Vec<_>>()
        .join(",\n");

    format!(
        r#"// Auto-generated by tenor ui. Do not edit.
import {{ useState, useEffect }} from 'react';
import {{ theme }} from '../theme';
import {{ ENTITIES, OPERATIONS, FLOWS, VERDICT_TYPES }} from '../types';
import {{ useEntities }} from '../hooks/useEntities';
import {{ useActionSpace }} from '../hooks/useActionSpace';
import {{ client, FlowExecution }} from '../api';

const ENTITY_LABELS = [
{entity_names_str}
];

export function Dashboard() {{
  const {{ instances, loading: entitiesLoading }} = useEntities();
  const {{ actionSpace }} = useActionSpace('', {{}});
  const [history, setHistory] = useState<FlowExecution[]>([]);
  const [historyLoading, setHistoryLoading] = useState(false);

  useEffect(() => {{
    setHistoryLoading(true);
    client.getExecutionHistory()
      .then((h) => setHistory(h.slice(0, 10)))
      .catch(() => {{}})
      .finally(() => setHistoryLoading(false));
  }}, []);

  return (
    <div style={{{{ padding: theme.spacing.lg }}}}>
      <h1 style={{{{ color: theme.colors.primary, marginBottom: theme.spacing.lg }}}}>Dashboard</h1>

      {{/* Entity overview */}}
      <section style={{{{ marginBottom: theme.spacing.xl }}}}>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.md }}}}>Entities</h2>
        <div style={{{{ display: 'flex', gap: theme.spacing.md, flexWrap: 'wrap' }}}}>
          {{ENTITY_LABELS.map((entity) => {{
            const entityInstances = instances[entity.id] ?? [];
            const stateCounts: Record<string, number> = {{}};
            for (const inst of entityInstances) {{
              stateCounts[inst.state] = (stateCounts[inst.state] ?? 0) + 1;
            }}
            return (
              <div
                key={{entity.id}}
                style={{{{
                  backgroundColor: theme.colors.surface,
                  border: `1px solid ${{theme.colors.border}}`,
                  borderRadius: theme.borderRadius.md,
                  padding: theme.spacing.md,
                  minWidth: '160px',
                }}}}
              >
                <div style={{{{ fontWeight: 600, marginBottom: theme.spacing.sm }}}}>{{entity.label}}</div>
                <div style={{{{ color: theme.colors.textSecondary, fontSize: '13px' }}}}>
                  {{entitiesLoading ? 'Loading...' : `${{entityInstances.length}} instance${{entityInstances.length !== 1 ? 's' : ''}}`}}
                </div>
                {{Object.entries(stateCounts).map(([state, count]) => (
                  <div key={{state}} style={{{{ fontSize: '12px', color: theme.colors.textSecondary }}}}>
                    {{state}}: {{count}}
                  </div>
                ))}}
              </div>
            );
          }})}}
        </div>
      </section>

      {{/* Action summary */}}
      <section style={{{{ marginBottom: theme.spacing.xl }}}}>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.md }}}}>Action Summary</h2>
        <div style={{{{ display: 'flex', gap: theme.spacing.lg }}}}>
          <div style={{{{ color: theme.colors.success }}}}>
            {{actionSpace ? `${{actionSpace.available.length}} available` : `${{OPERATIONS.length}} operations, ${{FLOWS.length}} flows`}}
          </div>
          <div style={{{{ color: theme.colors.warning }}}}>
            {{actionSpace ? `${{actionSpace.blocked.length}} blocked` : 'Select persona to see action space'}}
          </div>
        </div>
      </section>

      {{/* Verdict types */}}
      <section style={{{{ marginBottom: theme.spacing.xl }}}}>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.md }}}}>Verdict Types</h2>
        <div style={{{{ display: 'flex', gap: theme.spacing.sm, flexWrap: 'wrap' }}}}>
          {{VERDICT_TYPES.map((vt) => (
            <span
              key={{vt}}
              style={{{{
                backgroundColor: theme.colors.primaryLight,
                color: theme.colors.primary,
                borderRadius: theme.borderRadius.sm,
                padding: '2px 8px',
                fontSize: '12px',
              }}}}
            >
              {{vt}}
            </span>
          ))}}
        </div>
      </section>

      {{/* Recent activity */}}
      <section>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.md }}}}>Recent Activity</h2>
        {{historyLoading && <div style={{{{ color: theme.colors.textSecondary }}}}>Loading...</div>}}
        {{history.length === 0 && !historyLoading && (
          <div style={{{{ color: theme.colors.textSecondary }}}}>No recent executions.</div>
        )}}
        {{history.map((entry) => (
          <div
            key={{entry.execution_id}}
            style={{{{
              backgroundColor: theme.colors.surface,
              border: `1px solid ${{theme.colors.border}}`,
              borderRadius: theme.borderRadius.sm,
              padding: theme.spacing.sm,
              marginBottom: theme.spacing.sm,
              fontSize: '13px',
            }}}}
          >
            <span style={{{{ fontWeight: 600 }}}}>{{entry.flow_id}}</span>
            <span style={{{{ marginLeft: theme.spacing.sm, color: theme.colors.textSecondary }}}}>
              {{entry.persona}} — {{entry.outcome}}
            </span>
            <span style={{{{ marginLeft: theme.spacing.sm, color: theme.colors.textSecondary, fontSize: '11px' }}}}>
              {{new Date(entry.timestamp).toLocaleString()}}
            </span>
          </div>
        ))}}
      </section>
    </div>
  );
}}
"#,
        entity_names_str = entity_names_str,
    )
}

/// Generate `EntityList.tsx` content.
pub(super) fn emit_entity_list(bundle: &CodegenBundle) -> String {
    let entity_list: Vec<String> = bundle
        .entities
        .iter()
        .map(|e| {
            let pascal = to_pascal_case(&e.id);
            let states: Vec<String> = e.states.iter().map(|s| format!("\"{}\"", s)).collect();
            format!("  {{ id: '{}', states: [{}] }}", pascal, states.join(", "))
        })
        .collect();
    let entity_list_str = entity_list.join(",\n");

    format!(
        r#"// Auto-generated by tenor ui. Do not edit.
import {{ useNavigate }} from 'react-router-dom';
import {{ theme }} from '../theme';
import {{ useEntities }} from '../hooks/useEntities';

const ENTITY_DEFS = [
{entity_list_str}
];

export function EntityList() {{
  const navigate = useNavigate();
  const {{ instances, loading }} = useEntities();

  return (
    <div style={{{{ padding: theme.spacing.lg }}}}>
      <h1 style={{{{ color: theme.colors.primary, marginBottom: theme.spacing.lg }}}}>Entities</h1>
      {{loading && <div style={{{{ color: theme.colors.textSecondary }}}}>Loading instances...</div>}}
      <div style={{{{ display: 'flex', gap: theme.spacing.md, flexWrap: 'wrap' }}}}>
        {{ENTITY_DEFS.map((entity) => {{
          const entityInstances = instances[entity.id] ?? [];
          return (
            <div
              key={{entity.id}}
              onClick={{() => navigate(`/entities/${{entity.id}}`)}}
              style={{{{
                backgroundColor: theme.colors.surface,
                border: `1px solid ${{theme.colors.border}}`,
                borderRadius: theme.borderRadius.md,
                padding: theme.spacing.md,
                cursor: 'pointer',
                minWidth: '200px',
                transition: 'border-color 0.15s',
              }}}}
            >
              <h3 style={{{{ margin: '0 0 8px', color: theme.colors.primary }}}}>{{entity.id}}</h3>
              <div style={{{{ fontSize: '12px', color: theme.colors.textSecondary, marginBottom: '8px' }}}}>
                States: {{entity.states.join(', ')}}
              </div>
              <div style={{{{ fontSize: '13px', fontWeight: 600 }}}}>
                {{entityInstances.length}} instance{{entityInstances.length !== 1 ? 's' : ''}}
              </div>
            </div>
          );
        }})}}
      </div>
    </div>
  );
}}
"#,
        entity_list_str = entity_list_str,
    )
}

/// Generate `EntityDetail.tsx` content.
pub(super) fn emit_entity_detail(bundle: &CodegenBundle) -> String {
    let entity_map: Vec<String> = bundle
        .entities
        .iter()
        .map(|e| {
            let pascal = to_pascal_case(&e.id);
            let states: Vec<String> = e.states.iter().map(|s| format!("\"{}\"", s)).collect();
            let initial = e.states.first().map(|s| s.as_str()).unwrap_or("");
            format!(
                "  '{}': {{ states: [{}], initial: \"{}\" }}",
                pascal,
                states.join(", "),
                initial
            )
        })
        .collect();
    let entity_map_str = entity_map.join(",\n");

    let op_map: Vec<String> = bundle
        .operations
        .iter()
        .map(|op| format!("  '{}': '{}'", op.id, op.id))
        .collect();
    let op_map_str = op_map.join(",\n");
    let _ = op_map_str; // suppress unused warning

    format!(
        r#"// Auto-generated by tenor ui. Do not edit.
import {{ useParams, useNavigate }} from 'react-router-dom';
import {{ theme }} from '../theme';
import {{ useEntities }} from '../hooks/useEntities';

const ENTITY_MAP: Record<string, {{ states: string[]; initial: string }}> = {{
{entity_map_str}
}};

export function EntityDetail() {{
  const {{ id: entityId }} = useParams<{{ id: string }}>();
  const navigate = useNavigate();
  const {{ instances, loading }} = useEntities();

  if (!entityId) return <div>Entity not found.</div>;

  const entityDef = ENTITY_MAP[entityId];
  if (!entityDef) return <div style={{{{ color: theme.colors.error }}}}>Unknown entity: {{entityId}}</div>;

  const entityInstances = instances[entityId] ?? [];

  return (
    <div style={{{{ padding: theme.spacing.lg }}}}>
      <button
        onClick={{() => navigate('/entities')}}
        style={{{{ marginBottom: theme.spacing.md, cursor: 'pointer', background: 'none', border: 'none', color: theme.colors.primary, fontSize: '14px' }}}}
      >
        ← Back to Entities
      </button>
      <h1 style={{{{ color: theme.colors.primary, marginBottom: theme.spacing.md }}}}>{{entityId}}</h1>

      {{/* State machine */}}
      <section style={{{{ marginBottom: theme.spacing.xl }}}}>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.sm }}}}>States</h2>
        <div style={{{{ display: 'flex', gap: theme.spacing.sm, flexWrap: 'wrap' }}}}>
          {{entityDef.states.map((state) => (
            <span
              key={{state}}
              style={{{{
                backgroundColor: state === entityDef.initial ? theme.colors.primary : theme.colors.primaryLight,
                color: state === entityDef.initial ? theme.colors.surface : theme.colors.primary,
                borderRadius: theme.borderRadius.sm,
                padding: '4px 10px',
                fontSize: '13px',
                fontWeight: state === entityDef.initial ? 600 : 400,
              }}}}
            >
              {{state}}{{state === entityDef.initial ? ' (initial)' : ''}}
            </span>
          ))}}
        </div>
      </section>

      {{/* Instances */}}
      <section>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.sm }}}}>
          Instances {{loading ? '(loading...)' : `(${{entityInstances.length}})`}}
        </h2>
        {{entityInstances.length === 0 && !loading && (
          <div style={{{{ color: theme.colors.textSecondary }}}}>No instances found.</div>
        )}}
        {{entityInstances.map((inst) => (
          <div
            key={{inst.instance_id}}
            onClick={{() => navigate(`/entities/${{entityId}}/${{inst.instance_id}}`)}}
            style={{{{
              backgroundColor: theme.colors.surface,
              border: `1px solid ${{theme.colors.border}}`,
              borderRadius: theme.borderRadius.sm,
              padding: theme.spacing.sm,
              marginBottom: theme.spacing.sm,
              cursor: 'pointer',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
            }}}}
          >
            <span style={{{{ fontFamily: theme.fonts.mono, fontSize: '13px' }}}}>{{inst.instance_id}}</span>
            <span
              style={{{{
                backgroundColor: theme.colors.primaryLight,
                color: theme.colors.primary,
                borderRadius: theme.borderRadius.sm,
                padding: '2px 8px',
                fontSize: '12px',
              }}}}
            >
              {{inst.state}}
            </span>
          </div>
        ))}}
      </section>
    </div>
  );
}}
"#,
        entity_map_str = entity_map_str,
    )
}

/// Generate `InstanceDetail.tsx` content.
pub(super) fn emit_instance_detail(bundle: &CodegenBundle) -> String {
    let entity_states_map: Vec<String> = bundle
        .entities
        .iter()
        .map(|e| {
            let pascal = to_pascal_case(&e.id);
            let states: Vec<String> = e.states.iter().map(|s| format!("\"{}\"", s)).collect();
            format!("  '{}': [{}]", pascal, states.join(", "))
        })
        .collect();
    let entity_states_map_str = entity_states_map.join(",\n");

    format!(
        r#"// Auto-generated by tenor ui. Do not edit.
import {{ useParams, useNavigate }} from 'react-router-dom';
import {{ useState, useEffect }} from 'react';
import {{ theme }} from '../theme';
import {{ client, FlowExecution }} from '../api';

const ENTITY_STATES: Record<string, string[]> = {{
{entity_states_map_str}
}};

export function InstanceDetail() {{
  const {{ id: entityId, instanceId }} = useParams<{{ id: string; instanceId: string }}>();
  const navigate = useNavigate();
  const [state, setState] = useState<string | null>(null);
  const [history, setHistory] = useState<FlowExecution[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {{
    if (!entityId || !instanceId) return;
    setLoading(true);
    Promise.all([
      client.getEntityState(entityId, instanceId),
      client.getExecutionHistory(),
    ])
      .then(([s, h]) => {{
        setState(s);
        setHistory(
          h.filter((e) =>
            e.entity_state_changes.some(
              (c) => c.entity_id === entityId
            )
          ).slice(0, 20)
        );
      }})
      .catch(() => {{}})
      .finally(() => setLoading(false));
  }}, [entityId, instanceId]);

  if (!entityId || !instanceId) return <div>Instance not found.</div>;

  const entityStates = ENTITY_STATES[entityId] ?? [];

  return (
    <div style={{{{ padding: theme.spacing.lg }}}}>
      <button
        onClick={{() => navigate(`/entities/${{entityId}}`)}}
        style={{{{ marginBottom: theme.spacing.md, cursor: 'pointer', background: 'none', border: 'none', color: theme.colors.primary, fontSize: '14px' }}}}
      >
        ← Back to {{entityId}}
      </button>
      <h1 style={{{{ color: theme.colors.primary }}}}>
        {{entityId}} / <span style={{{{ fontFamily: theme.fonts.mono }}}}>{{instanceId}}</span>
      </h1>

      {{loading && <div style={{{{ color: theme.colors.textSecondary }}}}>Loading...</div>}}

      {{/* Current state */}}
      {{state && (
        <section style={{{{ marginBottom: theme.spacing.xl }}}}>
          <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.sm }}}}>Current State</h2>
          <div style={{{{ display: 'flex', gap: theme.spacing.sm, flexWrap: 'wrap' }}}}>
            {{entityStates.map((s) => (
              <span
                key={{s}}
                style={{{{
                  backgroundColor: s === state ? theme.colors.primary : theme.colors.primaryLight,
                  color: s === state ? theme.colors.surface : theme.colors.primary,
                  borderRadius: theme.borderRadius.sm,
                  padding: '4px 10px',
                  fontSize: '13px',
                  fontWeight: s === state ? 600 : 400,
                }}}}
              >
                {{s}}
              </span>
            ))}}
          </div>
        </section>
      )}}

      {{/* Execution history for this instance */}}
      <section>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.sm }}}}>Execution History</h2>
        {{history.length === 0 && !loading && (
          <div style={{{{ color: theme.colors.textSecondary }}}}>No executions involving this instance.</div>
        )}}
        {{history.map((entry) => (
          <div
            key={{entry.execution_id}}
            style={{{{
              backgroundColor: theme.colors.surface,
              border: `1px solid ${{theme.colors.border}}`,
              borderRadius: theme.borderRadius.sm,
              padding: theme.spacing.sm,
              marginBottom: theme.spacing.sm,
              fontSize: '13px',
            }}}}
          >
            <span style={{{{ fontWeight: 600 }}}}>{{entry.flow_id}}</span>
            <span style={{{{ marginLeft: theme.spacing.sm, color: theme.colors.textSecondary }}}}>
              {{entry.persona}} — {{entry.outcome}}
            </span>
            <div style={{{{ marginTop: '4px' }}}}>
              {{entry.entity_state_changes
                .filter((c) => c.entity_id === entityId)
                .map((c, i) => (
                  <span key={{i}} style={{{{ fontSize: '12px', color: theme.colors.textSecondary }}}}>
                    {{c.from_state}} → {{c.to_state}}
                  </span>
                ))}}
            </div>
          </div>
        ))}}
      </section>
    </div>
  );
}}
"#,
        entity_states_map_str = entity_states_map_str,
    )
}

/// Generate `BlockedActions.tsx` content.
pub(super) fn emit_blocked_actions() -> String {
    r#"// Auto-generated by tenor ui. Do not edit.
import { theme } from '../theme';
import { ActionSpaceAction } from '../api';

interface BlockedActionsProps {
  blocked: ActionSpaceAction[];
}

export function BlockedActions({ blocked }: BlockedActionsProps) {
  if (blocked.length === 0) return null;

  return (
    <div style={{ marginTop: '16px' }}>
      <h3 style={{ fontSize: '14px', color: theme.colors.warning, marginBottom: '8px' }}>
        Blocked Actions ({blocked.length})
      </h3>
      {blocked.map((action, i) => (
        <div
          key={i}
          style={{
            backgroundColor: '#fffbeb',
            border: `1px solid ${theme.colors.warning}`,
            borderRadius: theme.borderRadius.sm,
            padding: theme.spacing.sm,
            marginBottom: theme.spacing.sm,
          }}
        >
          <div style={{ fontWeight: 600, fontSize: '13px' }}>{action.flow_id}</div>
          {action.reason && (
            <div style={{ fontSize: '12px', color: theme.colors.textSecondary, marginTop: '4px' }}>
              {action.reason}
            </div>
          )}
          {action.enabling_verdicts && action.enabling_verdicts.length > 0 && (
            <div style={{ fontSize: '12px', marginTop: '4px' }}>
              <span style={{ color: theme.colors.textSecondary }}>Requires: </span>
              {action.enabling_verdicts.map((v, j) => (
                <span
                  key={j}
                  style={{
                    backgroundColor: theme.colors.primaryLight,
                    color: theme.colors.primary,
                    borderRadius: '3px',
                    padding: '1px 6px',
                    marginRight: '4px',
                    fontSize: '11px',
                  }}
                >
                  {v}
                </span>
              ))}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
"#
    .to_string()
}

// ─────────────────────────────────────────────────────────────────────────────
// ActionSpace, FactInput, FlowExecution (Task 4)
// ─────────────────────────────────────────────────────────────────────────────

/// Generate `ActionSpace.tsx` content.
pub(super) fn emit_action_space(_bundle: &CodegenBundle) -> String {
    r##"// Auto-generated by tenor ui. Do not edit.
import { useState, useCallback } from 'react';
import { theme } from '../theme';
import { PERSONAS } from '../types';
import { FactSet, InstanceBindingMap } from '../api';
import { useActionSpace } from '../hooks/useActionSpace';
import { useEntities } from '../hooks/useEntities';
import { useExecution } from '../hooks/useExecution';
import { BlockedActions } from './BlockedActions';
import { FactInput } from './FactInput';
import { FlowExecution } from './FlowExecution';

export function ActionSpace() {
  const [persona, setPersona] = useState<string>('');
  const [facts, setFacts] = useState<FactSet>({});
  const [instanceBindings, setInstanceBindings] = useState<InstanceBindingMap>({});
  const [selectedFlow, setSelectedFlow] = useState<string | null>(null);
  const [execMode, setExecMode] = useState<'execute' | 'simulate'>('execute');

  const { actionSpace, loading: asLoading, error: asError, refresh } = useActionSpace(persona, facts);
  const { instances } = useEntities();
  const { execute, simulate, result, loading: execLoading, error: execError } = useExecution();

  const handleFactChange = useCallback((updated: FactSet) => {
    setFacts(updated);
  }, []);

  const handleExecute = useCallback(
    async (flowId: string, mode: 'execute' | 'simulate') => {
      setSelectedFlow(flowId);
      setExecMode(mode);
      if (mode === 'execute') {
        await execute(flowId, persona, facts, instanceBindings);
      } else {
        await simulate(flowId, persona, facts, instanceBindings);
      }
      refresh();
    },
    [persona, facts, instanceBindings, execute, simulate, refresh]
  );

  return (
    <div style={{ padding: theme.spacing.lg }}>
      <h1 style={{ color: theme.colors.primary, marginBottom: theme.spacing.lg }}>Action Space</h1>

      {/* Persona selector */}
      <div style={{ marginBottom: theme.spacing.md }}>
        <label style={{ display: 'block', marginBottom: theme.spacing.xs, fontWeight: 600 }}>
          Persona
        </label>
        <select
          value={persona}
          onChange={(e) => setPersona(e.target.value)}
          style={{
            padding: '6px 10px',
            borderRadius: theme.borderRadius.sm,
            border: `1px solid ${theme.colors.border}`,
            fontSize: '14px',
            minWidth: '200px',
          }}
        >
          <option value="">Select persona...</option>
          {PERSONAS.map((p) => <option key={p} value={p}>{p}</option>)}
        </select>
      </div>

      {/* Fact input form */}
      <div style={{ marginBottom: theme.spacing.md }}>
        <h2 style={{ fontSize: '15px', marginBottom: theme.spacing.sm }}>Facts</h2>
        <FactInput facts={facts} onChange={handleFactChange} />
      </div>

      {/* Instance binding selectors (when multiple entity types are involved) */}
      {Object.keys(instances).length > 1 && (
        <div style={{ marginBottom: theme.spacing.md }}>
          <h2 style={{ fontSize: '15px', marginBottom: theme.spacing.sm }}>Select Instances</h2>
          {Object.entries(instances).map(([entityId, entityInstances]) => (
            <div key={entityId} style={{ marginBottom: theme.spacing.sm }}>
              <label style={{ display: 'block', marginBottom: theme.spacing.xs, fontSize: '13px', color: theme.colors.textSecondary }}>
                {entityId}
              </label>
              <select
                value={instanceBindings[entityId] ?? ''}
                onChange={(e) => setInstanceBindings((prev) => ({ ...prev, [entityId]: e.target.value }))}
                style={{
                  padding: '4px 8px',
                  borderRadius: theme.borderRadius.sm,
                  border: `1px solid ${theme.colors.border}`,
                  fontSize: '13px',
                }}
              >
                <option value="">Any instance</option>
                {entityInstances.map((inst) => (
                  <option key={inst.instance_id} value={inst.instance_id}>
                    {inst.instance_id} ({inst.state})
                  </option>
                ))}
              </select>
            </div>
          ))}
        </div>
      )}

      {/* Loading / error */}
      {asLoading && <div style={{ color: theme.colors.textSecondary }}>Computing action space...</div>}
      {asError && <div style={{ color: theme.colors.error }}>{asError}</div>}

      {/* Available actions */}
      {actionSpace && (
        <div>
          <h2 style={{ fontSize: '15px', marginBottom: theme.spacing.sm, color: theme.colors.success }}>
            Available Actions ({actionSpace.available.length})
          </h2>
          {actionSpace.available.map((action, i) => (
            <div
              key={i}
              style={{
                backgroundColor: theme.colors.surface,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: theme.borderRadius.sm,
                padding: theme.spacing.sm,
                marginBottom: theme.spacing.sm,
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
              }}
            >
              <span style={{ fontWeight: 600 }}>{action.flow_id}</span>
              <div style={{ display: 'flex', gap: theme.spacing.sm }}>
                <button
                  onClick={() => handleExecute(action.flow_id, 'execute')}
                  disabled={execLoading || !persona}
                  style={{
                    backgroundColor: theme.colors.primary,
                    color: theme.colors.surface,
                    border: 'none',
                    borderRadius: theme.borderRadius.sm,
                    padding: '4px 12px',
                    cursor: persona ? 'pointer' : 'not-allowed',
                    fontSize: '13px',
                  }}
                >
                  Execute
                </button>
                <button
                  onClick={() => handleExecute(action.flow_id, 'simulate')}
                  disabled={execLoading || !persona}
                  style={{
                    backgroundColor: theme.colors.secondary,
                    color: theme.colors.surface,
                    border: 'none',
                    borderRadius: theme.borderRadius.sm,
                    padding: '4px 12px',
                    cursor: persona ? 'pointer' : 'not-allowed',
                    fontSize: '13px',
                  }}
                >
                  Simulate
                </button>
              </div>
            </div>
          ))}
          <BlockedActions blocked={actionSpace.blocked} />
        </div>
      )}

      {/* Execution result */}
      {(result || execLoading || execError) && (
        <div style={{ marginTop: theme.spacing.lg }}>
          <FlowExecution
            flowId={selectedFlow ?? ''}
            mode={execMode}
            result={result}
            loading={execLoading}
            error={execError}
          />
        </div>
      )}
    </div>
  );
}
"##
    .to_string()
}

/// Generate `FactInput.tsx` content.
///
/// FactInput uses the FACTS metadata array from types.ts for runtime type dispatch.
/// The component renders a type-aware input for each fact based on its FactMeta.type.
pub(super) fn emit_fact_input(_bundle: &CodegenBundle) -> String {
    r##"// Auto-generated by tenor ui. Do not edit.
import { useState, useCallback } from 'react';
import { theme } from '../theme';
import { FACTS, FactMeta } from '../types';
import { FactSet } from '../api';

interface FactInputProps {
  facts: FactSet;
  onChange: (facts: FactSet) => void;
}

export function FactInput({ facts, onChange }: FactInputProps) {
  const handleChange = useCallback(
    (id: string, value: unknown) => {
      onChange({ ...facts, [id]: value });
    },
    [facts, onChange]
  );

  return (
    <div
      style={{
        backgroundColor: theme.colors.surface,
        border: `1px solid ${theme.colors.border}`,
        borderRadius: theme.borderRadius.md,
        padding: theme.spacing.md,
      }}
    >
      {FACTS.map((fact) => (
        <FactField
          key={fact.id}
          meta={fact}
          value={facts[fact.id]}
          onChange={(v) => handleChange(fact.id, v)}
        />
      ))}
    </div>
  );
}

interface FactFieldProps {
  meta: FactMeta;
  value: unknown;
  onChange: (value: unknown) => void;
}

function FactField({ meta, value, onChange }: FactFieldProps) {
  const labelStyle: React.CSSProperties = {
    display: 'block',
    marginBottom: '4px',
    fontSize: '13px',
    fontWeight: 600,
    color: theme.colors.textPrimary,
  };

  const inputStyle: React.CSSProperties = {
    padding: '6px 10px',
    borderRadius: theme.borderRadius.sm,
    border: `1px solid ${theme.colors.border}`,
    fontSize: '14px',
    width: '100%',
    boxSizing: 'border-box',
  };

  const wrapStyle: React.CSSProperties = {
    marginBottom: theme.spacing.sm,
  };

  switch (meta.type) {
    case 'Bool':
      return (
        <div style={{ ...wrapStyle, display: 'flex', alignItems: 'center', gap: '8px' }}>
          <input
            type="checkbox"
            id={`fact-${meta.id}`}
            checked={Boolean(value)}
            onChange={(e) => onChange(e.target.checked)}
          />
          <label htmlFor={`fact-${meta.id}`} style={{ fontSize: '13px', fontWeight: 600 }}>
            {meta.label}
          </label>
        </div>
      );

    case 'Int':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="number"
            step="1"
            value={typeof value === 'number' ? value : ''}
            onChange={(e) => onChange(e.target.valueAsNumber)}
            style={inputStyle}
          />
        </div>
      );

    case 'Decimal':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="number"
            step="any"
            value={typeof value === 'number' ? value : ''}
            onChange={(e) => onChange(e.target.valueAsNumber)}
            style={inputStyle}
          />
        </div>
      );

    case 'Text':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="text"
            value={typeof value === 'string' ? value : ''}
            onChange={(e) => onChange(e.target.value)}
            style={inputStyle}
          />
        </div>
      );

    case 'Date':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="date"
            value={typeof value === 'string' ? value : ''}
            onChange={(e) => onChange(e.target.value)}
            style={inputStyle}
          />
        </div>
      );

    case 'DateTime':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="datetime-local"
            value={typeof value === 'string' ? value : ''}
            onChange={(e) => onChange(e.target.value)}
            style={inputStyle}
          />
        </div>
      );

    case 'Money': {
      const moneyVal = (value && typeof value === 'object') ? value as { amount?: number; currency?: string } : {};
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <div style={{ display: 'flex', gap: '8px' }}>
            <input
              type="number"
              step="0.01"
              placeholder="Amount"
              value={moneyVal.amount ?? ''}
              onChange={(e) => onChange({ ...moneyVal, amount: e.target.valueAsNumber })}
              style={{ ...inputStyle, flex: 1 }}
            />
            <input
              type="text"
              placeholder={meta.currency ?? 'Currency'}
              value={moneyVal.currency ?? meta.currency ?? ''}
              onChange={(e) => onChange({ ...moneyVal, currency: e.target.value })}
              style={{ ...inputStyle, width: '80px', flex: 'none' }}
            />
          </div>
        </div>
      );
    }

    case 'Enum':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <select
            value={typeof value === 'string' ? value : ''}
            onChange={(e) => onChange(e.target.value)}
            style={inputStyle}
          >
            <option value="">Select...</option>
            {(meta.enumValues ?? []).map((opt) => (
              <option key={opt} value={opt}>{opt}</option>
            ))}
          </select>
        </div>
      );

    case 'List': {
      const listVal = Array.isArray(value) ? value as unknown[] : [];
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <div
            style={{
              border: `1px solid ${theme.colors.border}`,
              borderRadius: theme.borderRadius.sm,
              padding: '8px',
            }}
          >
            {listVal.map((item, idx) => (
              <div key={idx} style={{ display: 'flex', gap: '8px', marginBottom: '6px', alignItems: 'flex-start' }}>
                <div style={{ flex: 1 }}>
                  {meta.elementType && (
                    <FactField
                      meta={{ ...meta.elementType, id: `${meta.id}[${idx}]`, label: `Item ${idx + 1}` }}
                      value={item}
                      onChange={(v) => {
                        const updated = [...listVal];
                        updated[idx] = v;
                        onChange(updated);
                      }}
                    />
                  )}
                </div>
                <button
                  onClick={() => onChange(listVal.filter((_, i) => i !== idx))}
                  style={{
                    background: 'none',
                    border: `1px solid ${theme.colors.error}`,
                    borderRadius: theme.borderRadius.sm,
                    color: theme.colors.error,
                    cursor: 'pointer',
                    padding: '2px 8px',
                    fontSize: '12px',
                    flexShrink: 0,
                  }}
                >
                  Remove
                </button>
              </div>
            ))}
            <button
              onClick={() => onChange([...listVal, null])}
              style={{
                background: 'none',
                border: `1px solid ${theme.colors.primary}`,
                borderRadius: theme.borderRadius.sm,
                color: theme.colors.primary,
                cursor: 'pointer',
                padding: '4px 12px',
                fontSize: '13px',
              }}
            >
              + Add
            </button>
          </div>
        </div>
      );
    }

    case 'Record': {
      const recordVal = (value && typeof value === 'object' && !Array.isArray(value))
        ? value as Record<string, unknown>
        : {};
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <fieldset
            style={{
              border: `1px solid ${theme.colors.border}`,
              borderRadius: theme.borderRadius.sm,
              padding: '8px',
              margin: 0,
            }}
          >
            <legend style={{ fontSize: '12px', color: theme.colors.textSecondary }}>{meta.label}</legend>
            {Object.entries(meta.fields ?? {}).map(([fieldId, fieldMeta]) => (
              <FactField
                key={fieldId}
                meta={fieldMeta}
                value={recordVal[fieldId]}
                onChange={(v) => onChange({ ...recordVal, [fieldId]: v })}
              />
            ))}
          </fieldset>
        </div>
      );
    }

    default:
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="text"
            value={typeof value === 'string' ? value : JSON.stringify(value ?? '')}
            onChange={(e) => onChange(e.target.value)}
            style={inputStyle}
          />
        </div>
      );
  }
}
"##
    .to_string()
}

/// Generate `FlowExecution.tsx` content.
pub(super) fn emit_flow_execution() -> String {
    r#"// Auto-generated by tenor ui. Do not edit.
import { theme } from '../theme';
import { FlowResult } from '../api';

interface FlowExecutionProps {
  flowId: string;
  mode: 'execute' | 'simulate';
  result: FlowResult | null;
  loading: boolean;
  error: string | null;
}

export function FlowExecution({ flowId, mode, result, loading, error }: FlowExecutionProps) {
  if (loading) {
    return (
      <div style={{ color: theme.colors.textSecondary, padding: theme.spacing.md }}>
        {mode === 'simulate' ? 'Simulating' : 'Executing'} {flowId}...
      </div>
    );
  }

  if (error) {
    return (
      <div
        style={{
          backgroundColor: '#fef2f2',
          border: `1px solid ${theme.colors.error}`,
          borderRadius: theme.borderRadius.md,
          padding: theme.spacing.md,
          color: theme.colors.error,
        }}
      >
        <strong>Error:</strong> {error}
      </div>
    );
  }

  if (!result) return null;

  const isSimulation = result.simulation === true || mode === 'simulate';
  const outcomeColor =
    result.outcome === 'success' ? theme.colors.success : theme.colors.error;

  return (
    <div
      style={{
        backgroundColor: theme.colors.surface,
        border: `2px solid ${isSimulation ? theme.colors.secondary : theme.colors.border}`,
        borderRadius: theme.borderRadius.md,
        padding: theme.spacing.md,
      }}
    >
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: theme.spacing.md }}>
        <h3 style={{ margin: 0, color: theme.colors.primary }}>{result.flow_id}</h3>
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
          {isSimulation && (
            <span
              style={{
                backgroundColor: theme.colors.secondary,
                color: '#fff',
                borderRadius: theme.borderRadius.sm,
                padding: '2px 8px',
                fontSize: '12px',
                fontWeight: 600,
              }}
            >
              SIMULATION
            </span>
          )}
          <span
            style={{
              color: outcomeColor,
              fontWeight: 600,
              fontSize: '14px',
            }}
          >
            {result.outcome.toUpperCase()}
          </span>
        </div>
      </div>

      {/* State changes */}
      {result.entity_state_changes.length > 0 && (
        <div style={{ marginBottom: theme.spacing.md }}>
          <h4 style={{ fontSize: '13px', marginBottom: '6px' }}>State Changes</h4>
          <table
            style={{
              width: '100%',
              fontSize: '13px',
              borderCollapse: 'collapse',
            }}
          >
            <thead>
              <tr style={{ color: theme.colors.textSecondary }}>
                <th style={{ textAlign: 'left', paddingBottom: '4px' }}>Entity</th>
                <th style={{ textAlign: 'left', paddingBottom: '4px' }}>From</th>
                <th style={{ textAlign: 'left', paddingBottom: '4px' }}>To</th>
              </tr>
            </thead>
            <tbody>
              {result.entity_state_changes.map((change, i) => (
                <tr key={i}>
                  <td style={{ fontFamily: theme.fonts.mono }}>{change.entity_id}</td>
                  <td style={{ color: theme.colors.warning }}>{change.from_state}</td>
                  <td style={{ color: theme.colors.success }}>{change.to_state}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Steps executed */}
      {result.steps_executed.length > 0 && (
        <div style={{ marginBottom: theme.spacing.md }}>
          <h4 style={{ fontSize: '13px', marginBottom: '6px' }}>Steps Executed</h4>
          {result.steps_executed.map((step, i) => (
            <div
              key={i}
              style={{
                fontSize: '12px',
                color: theme.colors.textSecondary,
                fontFamily: theme.fonts.mono,
                marginBottom: '2px',
              }}
            >
              {step.step_id}: {step.result}
            </div>
          ))}
        </div>
      )}

      {/* Verdicts summary */}
      {result.verdicts.length > 0 && (
        <div>
          <h4 style={{ fontSize: '13px', marginBottom: '6px' }}>Verdicts</h4>
          {result.verdicts.map((v, i) => (
            <div
              key={i}
              style={{
                fontSize: '12px',
                display: 'flex',
                justifyContent: 'space-between',
                marginBottom: '2px',
              }}
            >
              <span style={{ color: theme.colors.info }}>{v.verdict_type}</span>
              <span style={{ fontFamily: theme.fonts.mono, color: theme.colors.textSecondary }}>
                {JSON.stringify(v.payload)}
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
"#
    .to_string()
}

// ─────────────────────────────────────────────────────────────────────────────
// Provenance, verdict, and history components (Task 5)
// ─────────────────────────────────────────────────────────────────────────────

/// Generate `ProvenanceDrill.tsx` content.
pub(super) fn emit_provenance_drill() -> String {
    r##"// Auto-generated by tenor ui. Do not edit.
import { useState } from 'react';
import { theme } from '../theme';
import { Verdict } from '../api';

interface ProvenanceDrillProps {
  verdicts: Verdict[];
}

interface TreeNodeProps {
  label: string;
  color: string;
  children?: React.ReactNode;
  defaultExpanded?: boolean;
}

function TreeNode({ label, color, children, defaultExpanded = false }: TreeNodeProps) {
  const [expanded, setExpanded] = useState(defaultExpanded);

  return (
    <div style={{ marginLeft: '12px' }}>
      <div
        onClick={() => setExpanded(!expanded)}
        style={{
          cursor: children ? 'pointer' : 'default',
          color,
          fontSize: '13px',
          padding: '2px 0',
          display: 'flex',
          alignItems: 'center',
          gap: '4px',
        }}
      >
        {children && <span>{expanded ? '▾' : '▸'}</span>}
        {!children && <span style={{ display: 'inline-block', width: '12px' }} />}
        <span>{label}</span>
      </div>
      {expanded && children && (
        <div style={{ borderLeft: `2px solid ${theme.colors.border}`, marginLeft: '6px' }}>
          {children}
        </div>
      )}
    </div>
  );
}

export function ProvenanceDrill({ verdicts }: ProvenanceDrillProps) {
  if (verdicts.length === 0) {
    return <div style={{ color: theme.colors.textSecondary }}>No provenance data available.</div>;
  }

  return (
    <div
      style={{
        backgroundColor: theme.colors.surface,
        border: `1px solid ${theme.colors.border}`,
        borderRadius: theme.borderRadius.md,
        padding: theme.spacing.md,
      }}
    >
      <h3 style={{ fontSize: '14px', marginBottom: theme.spacing.sm }}>Provenance</h3>
      {verdicts.map((verdict, i) => (
        <TreeNode
          key={i}
          label={`Verdict: ${verdict.verdict_type} = ${JSON.stringify(verdict.payload)}`}
          color={theme.colors.info}
          defaultExpanded={true}
        >
          <TreeNode
            label={`Rule: ${verdict.provenance.rule_id} (stratum ${verdict.provenance.stratum})`}
            color="#7c3aed"
            defaultExpanded={false}
          >
            {verdict.provenance.facts_examined.map((factId, j) => (
              <TreeNode
                key={j}
                label={`Fact: ${factId}`}
                color={theme.colors.success}
              />
            ))}
          </TreeNode>
        </TreeNode>
      ))}
    </div>
  );
}
"##
    .to_string()
}

/// Generate `VerdictDisplay.tsx` content.
pub(super) fn emit_verdict_display() -> String {
    r#"// Auto-generated by tenor ui. Do not edit.
import { theme } from '../theme';
import { Verdict } from '../api';
import { ProvenanceDrill } from './ProvenanceDrill';
import { useState } from 'react';

interface VerdictDisplayProps {
  verdicts: Verdict[];
}

export function VerdictDisplay({ verdicts }: VerdictDisplayProps) {
  const [selected, setSelected] = useState<Verdict | null>(null);

  if (verdicts.length === 0) {
    return <div style={{ color: theme.colors.textSecondary }}>No verdicts to display.</div>;
  }

  // Group verdicts by stratum
  const byStratum = new Map<number, Verdict[]>();
  for (const v of verdicts) {
    const s = v.provenance.stratum;
    const existing = byStratum.get(s) ?? [];
    byStratum.set(s, [...existing, v]);
  }

  const strata = Array.from(byStratum.keys()).sort((a, b) => a - b);

  return (
    <div>
      {strata.map((stratum) => (
        <div key={stratum} style={{ marginBottom: theme.spacing.md }}>
          <h4 style={{ fontSize: '13px', color: theme.colors.textSecondary, marginBottom: '6px' }}>
            Stratum {stratum}
          </h4>
          {(byStratum.get(stratum) ?? []).map((verdict, i) => {
            const isTruthy =
              verdict.payload === true ||
              (typeof verdict.payload === 'number' && verdict.payload !== 0) ||
              (typeof verdict.payload === 'string' && verdict.payload !== '');
            return (
              <div
                key={i}
                onClick={() => setSelected(selected === verdict ? null : verdict)}
                style={{
                  backgroundColor: theme.colors.surface,
                  border: `1px solid ${theme.colors.border}`,
                  borderRadius: theme.borderRadius.sm,
                  padding: '6px 10px',
                  marginBottom: '4px',
                  cursor: 'pointer',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span style={{ fontSize: '16px' }}>{isTruthy ? '✓' : '✗'}</span>
                  <span style={{ fontSize: '13px', color: theme.colors.info }}>
                    {verdict.verdict_type}
                  </span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span
                    style={{
                      fontFamily: theme.fonts.mono,
                      fontSize: '12px',
                      color: theme.colors.textSecondary,
                    }}
                  >
                    {JSON.stringify(verdict.payload)}
                  </span>
                  <span style={{ fontSize: '11px', color: theme.colors.textSecondary }}>
                    via {verdict.provenance.rule_id}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      ))}

      {selected && (
        <div style={{ marginTop: theme.spacing.md }}>
          <ProvenanceDrill verdicts={[selected]} />
        </div>
      )}
    </div>
  );
}
"#
    .to_string()
}

/// Generate `FlowHistory.tsx` content.
pub(super) fn emit_flow_history() -> String {
    r#"// Auto-generated by tenor ui. Do not edit.
import { useState, useEffect } from 'react';
import { theme } from '../theme';
import { client, FlowExecution } from '../api';
import { FLOWS, PERSONAS } from '../types';

export function FlowHistory() {
  const [history, setHistory] = useState<FlowExecution[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filterFlow, setFilterFlow] = useState('');
  const [filterPersona, setFilterPersona] = useState('');
  const [filterOutcome, setFilterOutcome] = useState('');
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  useEffect(() => {
    setLoading(true);
    client
      .getExecutionHistory()
      .then(setHistory)
      .catch((e) => setError(e instanceof Error ? e.message : String(e)))
      .finally(() => setLoading(false));
  }, []);

  const filtered = history.filter((entry) => {
    if (filterFlow && entry.flow_id !== filterFlow) return false;
    if (filterPersona && entry.persona !== filterPersona) return false;
    if (filterOutcome && entry.outcome !== filterOutcome) return false;
    return true;
  });

  const toggleExpanded = (id: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  return (
    <div style={{ padding: theme.spacing.lg }}>
      <h1 style={{ color: theme.colors.primary, marginBottom: theme.spacing.lg }}>
        Flow History
      </h1>

      {/* Filters */}
      <div style={{ display: 'flex', gap: theme.spacing.md, marginBottom: theme.spacing.md, flexWrap: 'wrap' }}>
        <select
          value={filterFlow}
          onChange={(e) => setFilterFlow(e.target.value)}
          style={{ padding: '6px 10px', borderRadius: theme.borderRadius.sm, border: `1px solid ${theme.colors.border}` }}
        >
          <option value="">All flows</option>
          {FLOWS.map((f) => (
            <option key={f.id} value={f.id}>{f.id}</option>
          ))}
        </select>

        <select
          value={filterPersona}
          onChange={(e) => setFilterPersona(e.target.value)}
          style={{ padding: '6px 10px', borderRadius: theme.borderRadius.sm, border: `1px solid ${theme.colors.border}` }}
        >
          <option value="">All personas</option>
          {PERSONAS.map((p) => (
            <option key={p} value={p}>{p}</option>
          ))}
        </select>

        <select
          value={filterOutcome}
          onChange={(e) => setFilterOutcome(e.target.value)}
          style={{ padding: '6px 10px', borderRadius: theme.borderRadius.sm, border: `1px solid ${theme.colors.border}` }}
        >
          <option value="">All outcomes</option>
          <option value="success">Success</option>
          <option value="failure">Failure</option>
        </select>
      </div>

      {loading && <div style={{ color: theme.colors.textSecondary }}>Loading history...</div>}
      {error && <div style={{ color: theme.colors.error }}>{error}</div>}

      {filtered.length === 0 && !loading && (
        <div style={{ color: theme.colors.textSecondary }}>No executions match the current filters.</div>
      )}

      {filtered.map((entry) => {
        const isExpanded = expanded.has(entry.execution_id);
        const outcomeColor =
          entry.outcome === 'success' ? theme.colors.success : theme.colors.error;
        return (
          <div
            key={entry.execution_id}
            style={{
              backgroundColor: theme.colors.surface,
              border: `1px solid ${theme.colors.border}`,
              borderRadius: theme.borderRadius.md,
              marginBottom: theme.spacing.sm,
              overflow: 'hidden',
            }}
          >
            <div
              onClick={() => toggleExpanded(entry.execution_id)}
              style={{
                padding: theme.spacing.sm,
                cursor: 'pointer',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
              }}
            >
              <div style={{ display: 'flex', gap: theme.spacing.md, alignItems: 'center' }}>
                <span style={{ fontSize: '12px' }}>{isExpanded ? '▾' : '▸'}</span>
                <span style={{ fontWeight: 600, fontSize: '13px' }}>{entry.flow_id}</span>
                <span style={{ color: theme.colors.textSecondary, fontSize: '12px' }}>
                  {entry.persona}
                </span>
              </div>
              <div style={{ display: 'flex', gap: theme.spacing.md, alignItems: 'center' }}>
                <span style={{ color: outcomeColor, fontWeight: 600, fontSize: '12px' }}>
                  {entry.outcome.toUpperCase()}
                </span>
                <span style={{ color: theme.colors.textSecondary, fontSize: '11px' }}>
                  {new Date(entry.timestamp).toLocaleString()}
                </span>
              </div>
            </div>
            {isExpanded && (
              <div
                style={{
                  padding: theme.spacing.sm,
                  borderTop: `1px solid ${theme.colors.border}`,
                  fontSize: '13px',
                }}
              >
                <div style={{ marginBottom: '4px', color: theme.colors.textSecondary, fontSize: '11px' }}>
                  ID: {entry.execution_id}
                </div>
                {entry.entity_state_changes.length > 0 && (
                  <div>
                    <strong style={{ fontSize: '12px' }}>State Changes:</strong>
                    {entry.entity_state_changes.map((change, i) => (
                      <div key={i} style={{ fontSize: '12px', paddingLeft: '8px' }}>
                        {change.entity_id}: {change.from_state} → {change.to_state}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
"#
    .to_string()
}
