//! Action space and blocked actions component generation.

use tenor_codegen::bundle::CodegenBundle;

/// Generate `BlockedActions.tsx` content.
pub(in crate::ui) fn emit_blocked_actions() -> String {
    r#"// Auto-generated by tenor ui. Do not edit.
import { theme } from '../theme';
import { ActionSpaceAction } from '../api';

interface BlockedActionsProps {
  blocked: ActionSpaceAction[];
}

export function BlockedActions({ blocked }: BlockedActionsProps) {
  if (blocked.length === 0) return null;

  return (
    <div style={{ marginTop: '16px' }}>
      <h3 style={{ fontSize: '14px', color: theme.colors.warning, marginBottom: '8px' }}>
        Blocked Actions ({blocked.length})
      </h3>
      {blocked.map((action, i) => (
        <div
          key={i}
          style={{
            backgroundColor: '#fffbeb',
            border: `1px solid ${theme.colors.warning}`,
            borderRadius: theme.borderRadius.sm,
            padding: theme.spacing.sm,
            marginBottom: theme.spacing.sm,
          }}
        >
          <div style={{ fontWeight: 600, fontSize: '13px' }}>{action.flow_id}</div>
          {action.reason && (
            <div style={{ fontSize: '12px', color: theme.colors.textSecondary, marginTop: '4px' }}>
              {action.reason}
            </div>
          )}
          {action.enabling_verdicts && action.enabling_verdicts.length > 0 && (
            <div style={{ fontSize: '12px', marginTop: '4px' }}>
              <span style={{ color: theme.colors.textSecondary }}>Requires: </span>
              {action.enabling_verdicts.map((v, j) => (
                <span
                  key={j}
                  style={{
                    backgroundColor: theme.colors.primaryLight,
                    color: theme.colors.primary,
                    borderRadius: '3px',
                    padding: '1px 6px',
                    marginRight: '4px',
                    fontSize: '11px',
                  }}
                >
                  {v}
                </span>
              ))}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
"#
    .to_string()
}

/// Generate `ActionSpace.tsx` content.
pub(in crate::ui) fn emit_action_space(_bundle: &CodegenBundle) -> String {
    r##"// Auto-generated by tenor ui. Do not edit.
import { useState, useCallback } from 'react';
import { theme } from '../theme';
import { PERSONAS } from '../types';
import { FactSet, InstanceBindingMap } from '../api';
import { useActionSpace } from '../hooks/useActionSpace';
import { useEntities } from '../hooks/useEntities';
import { useExecution } from '../hooks/useExecution';
import { BlockedActions } from './BlockedActions';
import { FactInput } from './FactInput';
import { FlowExecution } from './FlowExecution';

export function ActionSpace() {
  const [persona, setPersona] = useState<string>('');
  const [facts, setFacts] = useState<FactSet>({});
  const [instanceBindings, setInstanceBindings] = useState<InstanceBindingMap>({});
  const [selectedFlow, setSelectedFlow] = useState<string | null>(null);
  const [execMode, setExecMode] = useState<'execute' | 'simulate'>('execute');

  const { actionSpace, loading: asLoading, error: asError, refresh } = useActionSpace(persona, facts);
  const { instances } = useEntities();
  const { execute, simulate, result, loading: execLoading, error: execError } = useExecution();

  const handleFactChange = useCallback((updated: FactSet) => {
    setFacts(updated);
  }, []);

  const handleExecute = useCallback(
    async (flowId: string, mode: 'execute' | 'simulate') => {
      setSelectedFlow(flowId);
      setExecMode(mode);
      if (mode === 'execute') {
        await execute(flowId, persona, facts, instanceBindings);
      } else {
        await simulate(flowId, persona, facts, instanceBindings);
      }
      refresh();
    },
    [persona, facts, instanceBindings, execute, simulate, refresh]
  );

  return (
    <div style={{ padding: theme.spacing.lg }}>
      <h1 style={{ color: theme.colors.primary, marginBottom: theme.spacing.lg }}>Action Space</h1>

      {/* Persona selector */}
      <div style={{ marginBottom: theme.spacing.md }}>
        <label style={{ display: 'block', marginBottom: theme.spacing.xs, fontWeight: 600 }}>
          Persona
        </label>
        <select
          value={persona}
          onChange={(e) => setPersona(e.target.value)}
          style={{
            padding: '6px 10px',
            borderRadius: theme.borderRadius.sm,
            border: `1px solid ${theme.colors.border}`,
            fontSize: '14px',
            minWidth: '200px',
          }}
        >
          <option value="">Select persona...</option>
          {PERSONAS.map((p) => <option key={p} value={p}>{p}</option>)}
        </select>
      </div>

      {/* Fact input form */}
      <div style={{ marginBottom: theme.spacing.md }}>
        <h2 style={{ fontSize: '15px', marginBottom: theme.spacing.sm }}>Facts</h2>
        <FactInput facts={facts} onChange={handleFactChange} />
      </div>

      {/* Instance binding selectors (when multiple entity types are involved) */}
      {Object.keys(instances).length > 1 && (
        <div style={{ marginBottom: theme.spacing.md }}>
          <h2 style={{ fontSize: '15px', marginBottom: theme.spacing.sm }}>Select Instances</h2>
          {Object.entries(instances).map(([entityId, entityInstances]) => (
            <div key={entityId} style={{ marginBottom: theme.spacing.sm }}>
              <label style={{ display: 'block', marginBottom: theme.spacing.xs, fontSize: '13px', color: theme.colors.textSecondary }}>
                {entityId}
              </label>
              <select
                value={instanceBindings[entityId] ?? ''}
                onChange={(e) => setInstanceBindings((prev) => ({ ...prev, [entityId]: e.target.value }))}
                style={{
                  padding: '4px 8px',
                  borderRadius: theme.borderRadius.sm,
                  border: `1px solid ${theme.colors.border}`,
                  fontSize: '13px',
                }}
              >
                <option value="">Any instance</option>
                {entityInstances.map((inst) => (
                  <option key={inst.instance_id} value={inst.instance_id}>
                    {inst.instance_id} ({inst.state})
                  </option>
                ))}
              </select>
            </div>
          ))}
        </div>
      )}

      {/* Loading / error */}
      {asLoading && <div style={{ color: theme.colors.textSecondary }}>Computing action space...</div>}
      {asError && <div style={{ color: theme.colors.error }}>{asError}</div>}

      {/* Available actions */}
      {actionSpace && (
        <div>
          <h2 style={{ fontSize: '15px', marginBottom: theme.spacing.sm, color: theme.colors.success }}>
            Available Actions ({actionSpace.available.length})
          </h2>
          {actionSpace.available.map((action, i) => (
            <div
              key={i}
              style={{
                backgroundColor: theme.colors.surface,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: theme.borderRadius.sm,
                padding: theme.spacing.sm,
                marginBottom: theme.spacing.sm,
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
              }}
            >
              <span style={{ fontWeight: 600 }}>{action.flow_id}</span>
              <div style={{ display: 'flex', gap: theme.spacing.sm }}>
                <button
                  onClick={() => handleExecute(action.flow_id, 'execute')}
                  disabled={execLoading || !persona}
                  style={{
                    backgroundColor: theme.colors.primary,
                    color: theme.colors.surface,
                    border: 'none',
                    borderRadius: theme.borderRadius.sm,
                    padding: '4px 12px',
                    cursor: persona ? 'pointer' : 'not-allowed',
                    fontSize: '13px',
                  }}
                >
                  Execute
                </button>
                <button
                  onClick={() => handleExecute(action.flow_id, 'simulate')}
                  disabled={execLoading || !persona}
                  style={{
                    backgroundColor: theme.colors.secondary,
                    color: theme.colors.surface,
                    border: 'none',
                    borderRadius: theme.borderRadius.sm,
                    padding: '4px 12px',
                    cursor: persona ? 'pointer' : 'not-allowed',
                    fontSize: '13px',
                  }}
                >
                  Simulate
                </button>
              </div>
            </div>
          ))}
          <BlockedActions blocked={actionSpace.blocked} />
        </div>
      )}

      {/* Execution result */}
      {(result || execLoading || execError) && (
        <div style={{ marginTop: theme.spacing.lg }}>
          <FlowExecution
            flowId={selectedFlow ?? ''}
            mode={execMode}
            result={result}
            loading={execLoading}
            error={execError}
          />
        </div>
      )}
    </div>
  );
}
"##
    .to_string()
}
