//! Dashboard component generation.

use tenor_codegen::bundle::CodegenBundle;
use tenor_codegen::typescript::to_pascal_case;

/// Generate `Dashboard.tsx` content.
pub(in crate::ui) fn emit_dashboard(bundle: &CodegenBundle) -> String {
    let entity_names: Vec<String> = bundle
        .entities
        .iter()
        .map(|e| to_pascal_case(&e.id))
        .collect();
    let entity_names_str = entity_names
        .iter()
        .map(|n| format!("    {{ id: '{}', label: '{}' }}", n, n))
        .collect::<Vec<_>>()
        .join(",\n");

    format!(
        r#"// Auto-generated by tenor ui. Do not edit.
import {{ useState, useEffect }} from 'react';
import {{ theme }} from '../theme';
import {{ ENTITIES, OPERATIONS, FLOWS, VERDICT_TYPES }} from '../types';
import {{ useEntities }} from '../hooks/useEntities';
import {{ useActionSpace }} from '../hooks/useActionSpace';
import {{ client, FlowExecution }} from '../api';

const ENTITY_LABELS = [
{entity_names_str}
];

export function Dashboard() {{
  const {{ instances, loading: entitiesLoading }} = useEntities();
  const {{ actionSpace }} = useActionSpace('', {{}});
  const [history, setHistory] = useState<FlowExecution[]>([]);
  const [historyLoading, setHistoryLoading] = useState(false);

  useEffect(() => {{
    setHistoryLoading(true);
    client.getExecutionHistory()
      .then((h) => setHistory(h.slice(0, 10)))
      .catch(() => {{}})
      .finally(() => setHistoryLoading(false));
  }}, []);

  return (
    <div style={{{{ padding: theme.spacing.lg }}}}>
      <h1 style={{{{ color: theme.colors.primary, marginBottom: theme.spacing.lg }}}}>Dashboard</h1>

      {{/* Entity overview */}}
      <section style={{{{ marginBottom: theme.spacing.xl }}}}>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.md }}}}>Entities</h2>
        <div style={{{{ display: 'flex', gap: theme.spacing.md, flexWrap: 'wrap' }}}}>
          {{ENTITY_LABELS.map((entity) => {{
            const entityInstances = instances[entity.id] ?? [];
            const stateCounts: Record<string, number> = {{}};
            for (const inst of entityInstances) {{
              stateCounts[inst.state] = (stateCounts[inst.state] ?? 0) + 1;
            }}
            return (
              <div
                key={{entity.id}}
                style={{{{
                  backgroundColor: theme.colors.surface,
                  border: `1px solid ${{theme.colors.border}}`,
                  borderRadius: theme.borderRadius.md,
                  padding: theme.spacing.md,
                  minWidth: '160px',
                }}}}
              >
                <div style={{{{ fontWeight: 600, marginBottom: theme.spacing.sm }}}}>{{entity.label}}</div>
                <div style={{{{ color: theme.colors.textSecondary, fontSize: '13px' }}}}>
                  {{entitiesLoading ? 'Loading...' : `${{entityInstances.length}} instance${{entityInstances.length !== 1 ? 's' : ''}}`}}
                </div>
                {{Object.entries(stateCounts).map(([state, count]) => (
                  <div key={{state}} style={{{{ fontSize: '12px', color: theme.colors.textSecondary }}}}>
                    {{state}}: {{count}}
                  </div>
                ))}}
              </div>
            );
          }})}}
        </div>
      </section>

      {{/* Action summary */}}
      <section style={{{{ marginBottom: theme.spacing.xl }}}}>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.md }}}}>Action Summary</h2>
        <div style={{{{ display: 'flex', gap: theme.spacing.lg }}}}>
          <div style={{{{ color: theme.colors.success }}}}>
            {{actionSpace ? `${{actionSpace.available.length}} available` : `${{OPERATIONS.length}} operations, ${{FLOWS.length}} flows`}}
          </div>
          <div style={{{{ color: theme.colors.warning }}}}>
            {{actionSpace ? `${{actionSpace.blocked.length}} blocked` : 'Select persona to see action space'}}
          </div>
        </div>
      </section>

      {{/* Verdict types */}}
      <section style={{{{ marginBottom: theme.spacing.xl }}}}>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.md }}}}>Verdict Types</h2>
        <div style={{{{ display: 'flex', gap: theme.spacing.sm, flexWrap: 'wrap' }}}}>
          {{VERDICT_TYPES.map((vt) => (
            <span
              key={{vt}}
              style={{{{
                backgroundColor: theme.colors.primaryLight,
                color: theme.colors.primary,
                borderRadius: theme.borderRadius.sm,
                padding: '2px 8px',
                fontSize: '12px',
              }}}}
            >
              {{vt}}
            </span>
          ))}}
        </div>
      </section>

      {{/* Recent activity */}}
      <section>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.md }}}}>Recent Activity</h2>
        {{historyLoading && <div style={{{{ color: theme.colors.textSecondary }}}}>Loading...</div>}}
        {{history.length === 0 && !historyLoading && (
          <div style={{{{ color: theme.colors.textSecondary }}}}>No recent executions.</div>
        )}}
        {{history.map((entry) => (
          <div
            key={{entry.execution_id}}
            style={{{{
              backgroundColor: theme.colors.surface,
              border: `1px solid ${{theme.colors.border}}`,
              borderRadius: theme.borderRadius.sm,
              padding: theme.spacing.sm,
              marginBottom: theme.spacing.sm,
              fontSize: '13px',
            }}}}
          >
            <span style={{{{ fontWeight: 600 }}}}>{{entry.flow_id}}</span>
            <span style={{{{ marginLeft: theme.spacing.sm, color: theme.colors.textSecondary }}}}>
              {{entry.persona}} — {{entry.outcome}}
            </span>
            <span style={{{{ marginLeft: theme.spacing.sm, color: theme.colors.textSecondary, fontSize: '11px' }}}}>
              {{new Date(entry.timestamp).toLocaleString()}}
            </span>
          </div>
        ))}}
      </section>
    </div>
  );
}}
"#,
        entity_names_str = entity_names_str,
    )
}
