//! Entity-related component generation (EntityList, EntityDetail, InstanceDetail).

use tenor_codegen::bundle::CodegenBundle;
use tenor_codegen::typescript::to_pascal_case;

/// Generate `EntityList.tsx` content.
pub(in crate::ui) fn emit_entity_list(bundle: &CodegenBundle) -> String {
    let entity_list: Vec<String> = bundle
        .entities
        .iter()
        .map(|e| {
            let pascal = to_pascal_case(&e.id);
            let states: Vec<String> = e.states.iter().map(|s| format!("\"{}\"", s)).collect();
            format!("  {{ id: '{}', states: [{}] }}", pascal, states.join(", "))
        })
        .collect();
    let entity_list_str = entity_list.join(",\n");

    format!(
        r#"// Auto-generated by tenor ui. Do not edit.
import {{ useNavigate }} from 'react-router-dom';
import {{ theme }} from '../theme';
import {{ useEntities }} from '../hooks/useEntities';

const ENTITY_DEFS = [
{entity_list_str}
];

export function EntityList() {{
  const navigate = useNavigate();
  const {{ instances, loading }} = useEntities();

  return (
    <div style={{{{ padding: theme.spacing.lg }}}}>
      <h1 style={{{{ color: theme.colors.primary, marginBottom: theme.spacing.lg }}}}>Entities</h1>
      {{loading && <div style={{{{ color: theme.colors.textSecondary }}}}>Loading instances...</div>}}
      <div style={{{{ display: 'flex', gap: theme.spacing.md, flexWrap: 'wrap' }}}}>
        {{ENTITY_DEFS.map((entity) => {{
          const entityInstances = instances[entity.id] ?? [];
          return (
            <div
              key={{entity.id}}
              onClick={{() => navigate(`/entities/${{entity.id}}`)}}
              style={{{{
                backgroundColor: theme.colors.surface,
                border: `1px solid ${{theme.colors.border}}`,
                borderRadius: theme.borderRadius.md,
                padding: theme.spacing.md,
                cursor: 'pointer',
                minWidth: '200px',
                transition: 'border-color 0.15s',
              }}}}
            >
              <h3 style={{{{ margin: '0 0 8px', color: theme.colors.primary }}}}>{{entity.id}}</h3>
              <div style={{{{ fontSize: '12px', color: theme.colors.textSecondary, marginBottom: '8px' }}}}>
                States: {{entity.states.join(', ')}}
              </div>
              <div style={{{{ fontSize: '13px', fontWeight: 600 }}}}>
                {{entityInstances.length}} instance{{entityInstances.length !== 1 ? 's' : ''}}
              </div>
            </div>
          );
        }})}}
      </div>
    </div>
  );
}}
"#,
        entity_list_str = entity_list_str,
    )
}

/// Generate `EntityDetail.tsx` content.
pub(in crate::ui) fn emit_entity_detail(bundle: &CodegenBundle) -> String {
    let entity_map: Vec<String> = bundle
        .entities
        .iter()
        .map(|e| {
            let pascal = to_pascal_case(&e.id);
            let states: Vec<String> = e.states.iter().map(|s| format!("\"{}\"", s)).collect();
            let initial = e.states.first().map(|s| s.as_str()).unwrap_or("");
            format!(
                "  '{}': {{ states: [{}], initial: \"{}\" }}",
                pascal,
                states.join(", "),
                initial
            )
        })
        .collect();
    let entity_map_str = entity_map.join(",\n");

    let op_map: Vec<String> = bundle
        .operations
        .iter()
        .map(|op| format!("  '{}': '{}'", op.id, op.id))
        .collect();
    let op_map_str = op_map.join(",\n");
    let _ = op_map_str; // suppress unused warning

    format!(
        r#"// Auto-generated by tenor ui. Do not edit.
import {{ useParams, useNavigate }} from 'react-router-dom';
import {{ theme }} from '../theme';
import {{ useEntities }} from '../hooks/useEntities';

const ENTITY_MAP: Record<string, {{ states: string[]; initial: string }}> = {{
{entity_map_str}
}};

export function EntityDetail() {{
  const {{ id: entityId }} = useParams<{{ id: string }}>();
  const navigate = useNavigate();
  const {{ instances, loading }} = useEntities();

  if (!entityId) return <div>Entity not found.</div>;

  const entityDef = ENTITY_MAP[entityId];
  if (!entityDef) return <div style={{{{ color: theme.colors.error }}}}>Unknown entity: {{entityId}}</div>;

  const entityInstances = instances[entityId] ?? [];

  return (
    <div style={{{{ padding: theme.spacing.lg }}}}>
      <button
        onClick={{() => navigate('/entities')}}
        style={{{{ marginBottom: theme.spacing.md, cursor: 'pointer', background: 'none', border: 'none', color: theme.colors.primary, fontSize: '14px' }}}}
      >
        ← Back to Entities
      </button>
      <h1 style={{{{ color: theme.colors.primary, marginBottom: theme.spacing.md }}}}>{{entityId}}</h1>

      {{/* State machine */}}
      <section style={{{{ marginBottom: theme.spacing.xl }}}}>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.sm }}}}>States</h2>
        <div style={{{{ display: 'flex', gap: theme.spacing.sm, flexWrap: 'wrap' }}}}>
          {{entityDef.states.map((state) => (
            <span
              key={{state}}
              style={{{{
                backgroundColor: state === entityDef.initial ? theme.colors.primary : theme.colors.primaryLight,
                color: state === entityDef.initial ? theme.colors.surface : theme.colors.primary,
                borderRadius: theme.borderRadius.sm,
                padding: '4px 10px',
                fontSize: '13px',
                fontWeight: state === entityDef.initial ? 600 : 400,
              }}}}
            >
              {{state}}{{state === entityDef.initial ? ' (initial)' : ''}}
            </span>
          ))}}
        </div>
      </section>

      {{/* Instances */}}
      <section>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.sm }}}}>
          Instances {{loading ? '(loading...)' : `(${{entityInstances.length}})`}}
        </h2>
        {{entityInstances.length === 0 && !loading && (
          <div style={{{{ color: theme.colors.textSecondary }}}}>No instances found.</div>
        )}}
        {{entityInstances.map((inst) => (
          <div
            key={{inst.instance_id}}
            onClick={{() => navigate(`/entities/${{entityId}}/${{inst.instance_id}}`)}}
            style={{{{
              backgroundColor: theme.colors.surface,
              border: `1px solid ${{theme.colors.border}}`,
              borderRadius: theme.borderRadius.sm,
              padding: theme.spacing.sm,
              marginBottom: theme.spacing.sm,
              cursor: 'pointer',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
            }}}}
          >
            <span style={{{{ fontFamily: theme.fonts.mono, fontSize: '13px' }}}}>{{inst.instance_id}}</span>
            <span
              style={{{{
                backgroundColor: theme.colors.primaryLight,
                color: theme.colors.primary,
                borderRadius: theme.borderRadius.sm,
                padding: '2px 8px',
                fontSize: '12px',
              }}}}
            >
              {{inst.state}}
            </span>
          </div>
        ))}}
      </section>
    </div>
  );
}}
"#,
        entity_map_str = entity_map_str,
    )
}

/// Generate `InstanceDetail.tsx` content.
pub(in crate::ui) fn emit_instance_detail(bundle: &CodegenBundle) -> String {
    let entity_states_map: Vec<String> = bundle
        .entities
        .iter()
        .map(|e| {
            let pascal = to_pascal_case(&e.id);
            let states: Vec<String> = e.states.iter().map(|s| format!("\"{}\"", s)).collect();
            format!("  '{}': [{}]", pascal, states.join(", "))
        })
        .collect();
    let entity_states_map_str = entity_states_map.join(",\n");

    format!(
        r#"// Auto-generated by tenor ui. Do not edit.
import {{ useParams, useNavigate }} from 'react-router-dom';
import {{ useState, useEffect }} from 'react';
import {{ theme }} from '../theme';
import {{ client, FlowExecution }} from '../api';

const ENTITY_STATES: Record<string, string[]> = {{
{entity_states_map_str}
}};

export function InstanceDetail() {{
  const {{ id: entityId, instanceId }} = useParams<{{ id: string; instanceId: string }}>();
  const navigate = useNavigate();
  const [state, setState] = useState<string | null>(null);
  const [history, setHistory] = useState<FlowExecution[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {{
    if (!entityId || !instanceId) return;
    setLoading(true);
    Promise.all([
      client.getEntityState(entityId, instanceId),
      client.getExecutionHistory(),
    ])
      .then(([s, h]) => {{
        setState(s);
        setHistory(
          h.filter((e) =>
            e.entity_state_changes.some(
              (c) => c.entity_id === entityId
            )
          ).slice(0, 20)
        );
      }})
      .catch(() => {{}})
      .finally(() => setLoading(false));
  }}, [entityId, instanceId]);

  if (!entityId || !instanceId) return <div>Instance not found.</div>;

  const entityStates = ENTITY_STATES[entityId] ?? [];

  return (
    <div style={{{{ padding: theme.spacing.lg }}}}>
      <button
        onClick={{() => navigate(`/entities/${{entityId}}`)}}
        style={{{{ marginBottom: theme.spacing.md, cursor: 'pointer', background: 'none', border: 'none', color: theme.colors.primary, fontSize: '14px' }}}}
      >
        ← Back to {{entityId}}
      </button>
      <h1 style={{{{ color: theme.colors.primary }}}}>
        {{entityId}} / <span style={{{{ fontFamily: theme.fonts.mono }}}}>{{instanceId}}</span>
      </h1>

      {{loading && <div style={{{{ color: theme.colors.textSecondary }}}}>Loading...</div>}}

      {{/* Current state */}}
      {{state && (
        <section style={{{{ marginBottom: theme.spacing.xl }}}}>
          <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.sm }}}}>Current State</h2>
          <div style={{{{ display: 'flex', gap: theme.spacing.sm, flexWrap: 'wrap' }}}}>
            {{entityStates.map((s) => (
              <span
                key={{s}}
                style={{{{
                  backgroundColor: s === state ? theme.colors.primary : theme.colors.primaryLight,
                  color: s === state ? theme.colors.surface : theme.colors.primary,
                  borderRadius: theme.borderRadius.sm,
                  padding: '4px 10px',
                  fontSize: '13px',
                  fontWeight: s === state ? 600 : 400,
                }}}}
              >
                {{s}}
              </span>
            ))}}
          </div>
        </section>
      )}}

      {{/* Execution history for this instance */}}
      <section>
        <h2 style={{{{ fontSize: '16px', marginBottom: theme.spacing.sm }}}}>Execution History</h2>
        {{history.length === 0 && !loading && (
          <div style={{{{ color: theme.colors.textSecondary }}}}>No executions involving this instance.</div>
        )}}
        {{history.map((entry) => (
          <div
            key={{entry.execution_id}}
            style={{{{
              backgroundColor: theme.colors.surface,
              border: `1px solid ${{theme.colors.border}}`,
              borderRadius: theme.borderRadius.sm,
              padding: theme.spacing.sm,
              marginBottom: theme.spacing.sm,
              fontSize: '13px',
            }}}}
          >
            <span style={{{{ fontWeight: 600 }}}}>{{entry.flow_id}}</span>
            <span style={{{{ marginLeft: theme.spacing.sm, color: theme.colors.textSecondary }}}}>
              {{entry.persona}} — {{entry.outcome}}
            </span>
            <div style={{{{ marginTop: '4px' }}}}>
              {{entry.entity_state_changes
                .filter((c) => c.entity_id === entityId)
                .map((c, i) => (
                  <span key={{i}} style={{{{ fontSize: '12px', color: theme.colors.textSecondary }}}}>
                    {{c.from_state}} → {{c.to_state}}
                  </span>
                ))}}
            </div>
          </div>
        ))}}
      </section>
    </div>
  );
}}
"#,
        entity_states_map_str = entity_states_map_str,
    )
}
