//! Fact input form component generation.

use tenor_codegen::bundle::CodegenBundle;

/// Generate `FactInput.tsx` content.
///
/// FactInput uses the FACTS metadata array from types.ts for runtime type dispatch.
/// The component renders a type-aware input for each fact based on its FactMeta.type.
pub(in crate::ui) fn emit_fact_input(_bundle: &CodegenBundle) -> String {
    r##"// Auto-generated by tenor ui. Do not edit.
import { useState, useCallback } from 'react';
import { theme } from '../theme';
import { FACTS, FactMeta } from '../types';
import { FactSet } from '../api';

interface FactInputProps {
  facts: FactSet;
  onChange: (facts: FactSet) => void;
}

export function FactInput({ facts, onChange }: FactInputProps) {
  const handleChange = useCallback(
    (id: string, value: unknown) => {
      onChange({ ...facts, [id]: value });
    },
    [facts, onChange]
  );

  return (
    <div
      style={{
        backgroundColor: theme.colors.surface,
        border: `1px solid ${theme.colors.border}`,
        borderRadius: theme.borderRadius.md,
        padding: theme.spacing.md,
      }}
    >
      {FACTS.map((fact) => (
        <FactField
          key={fact.id}
          meta={fact}
          value={facts[fact.id]}
          onChange={(v) => handleChange(fact.id, v)}
        />
      ))}
    </div>
  );
}

interface FactFieldProps {
  meta: FactMeta;
  value: unknown;
  onChange: (value: unknown) => void;
}

function FactField({ meta, value, onChange }: FactFieldProps) {
  const labelStyle: React.CSSProperties = {
    display: 'block',
    marginBottom: '4px',
    fontSize: '13px',
    fontWeight: 600,
    color: theme.colors.textPrimary,
  };

  const inputStyle: React.CSSProperties = {
    padding: '6px 10px',
    borderRadius: theme.borderRadius.sm,
    border: `1px solid ${theme.colors.border}`,
    fontSize: '14px',
    width: '100%',
    boxSizing: 'border-box',
  };

  const wrapStyle: React.CSSProperties = {
    marginBottom: theme.spacing.sm,
  };

  switch (meta.type) {
    case 'Bool':
      return (
        <div style={{ ...wrapStyle, display: 'flex', alignItems: 'center', gap: '8px' }}>
          <input
            type="checkbox"
            id={`fact-${meta.id}`}
            checked={Boolean(value)}
            onChange={(e) => onChange(e.target.checked)}
          />
          <label htmlFor={`fact-${meta.id}`} style={{ fontSize: '13px', fontWeight: 600 }}>
            {meta.label}
          </label>
        </div>
      );

    case 'Int':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="number"
            step="1"
            value={typeof value === 'number' ? value : ''}
            onChange={(e) => onChange(e.target.valueAsNumber)}
            style={inputStyle}
          />
        </div>
      );

    case 'Decimal':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="number"
            step="any"
            value={typeof value === 'number' ? value : ''}
            onChange={(e) => onChange(e.target.valueAsNumber)}
            style={inputStyle}
          />
        </div>
      );

    case 'Text':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="text"
            value={typeof value === 'string' ? value : ''}
            onChange={(e) => onChange(e.target.value)}
            style={inputStyle}
          />
        </div>
      );

    case 'Date':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="date"
            value={typeof value === 'string' ? value : ''}
            onChange={(e) => onChange(e.target.value)}
            style={inputStyle}
          />
        </div>
      );

    case 'DateTime':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="datetime-local"
            value={typeof value === 'string' ? value : ''}
            onChange={(e) => onChange(e.target.value)}
            style={inputStyle}
          />
        </div>
      );

    case 'Money': {
      const moneyVal = (value && typeof value === 'object') ? value as { amount?: number; currency?: string } : {};
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <div style={{ display: 'flex', gap: '8px' }}>
            <input
              type="number"
              step="0.01"
              placeholder="Amount"
              value={moneyVal.amount ?? ''}
              onChange={(e) => onChange({ ...moneyVal, amount: e.target.valueAsNumber })}
              style={{ ...inputStyle, flex: 1 }}
            />
            <input
              type="text"
              placeholder={meta.currency ?? 'Currency'}
              value={moneyVal.currency ?? meta.currency ?? ''}
              onChange={(e) => onChange({ ...moneyVal, currency: e.target.value })}
              style={{ ...inputStyle, width: '80px', flex: 'none' }}
            />
          </div>
        </div>
      );
    }

    case 'Enum':
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <select
            value={typeof value === 'string' ? value : ''}
            onChange={(e) => onChange(e.target.value)}
            style={inputStyle}
          >
            <option value="">Select...</option>
            {(meta.enumValues ?? []).map((opt) => (
              <option key={opt} value={opt}>{opt}</option>
            ))}
          </select>
        </div>
      );

    case 'List': {
      const listVal = Array.isArray(value) ? value as unknown[] : [];
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <div
            style={{
              border: `1px solid ${theme.colors.border}`,
              borderRadius: theme.borderRadius.sm,
              padding: '8px',
            }}
          >
            {listVal.map((item, idx) => (
              <div key={idx} style={{ display: 'flex', gap: '8px', marginBottom: '6px', alignItems: 'flex-start' }}>
                <div style={{ flex: 1 }}>
                  {meta.elementType && (
                    <FactField
                      meta={{ ...meta.elementType, id: `${meta.id}[${idx}]`, label: `Item ${idx + 1}` }}
                      value={item}
                      onChange={(v) => {
                        const updated = [...listVal];
                        updated[idx] = v;
                        onChange(updated);
                      }}
                    />
                  )}
                </div>
                <button
                  onClick={() => onChange(listVal.filter((_, i) => i !== idx))}
                  style={{
                    background: 'none',
                    border: `1px solid ${theme.colors.error}`,
                    borderRadius: theme.borderRadius.sm,
                    color: theme.colors.error,
                    cursor: 'pointer',
                    padding: '2px 8px',
                    fontSize: '12px',
                    flexShrink: 0,
                  }}
                >
                  Remove
                </button>
              </div>
            ))}
            <button
              onClick={() => onChange([...listVal, null])}
              style={{
                background: 'none',
                border: `1px solid ${theme.colors.primary}`,
                borderRadius: theme.borderRadius.sm,
                color: theme.colors.primary,
                cursor: 'pointer',
                padding: '4px 12px',
                fontSize: '13px',
              }}
            >
              + Add
            </button>
          </div>
        </div>
      );
    }

    case 'Record': {
      const recordVal = (value && typeof value === 'object' && !Array.isArray(value))
        ? value as Record<string, unknown>
        : {};
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <fieldset
            style={{
              border: `1px solid ${theme.colors.border}`,
              borderRadius: theme.borderRadius.sm,
              padding: '8px',
              margin: 0,
            }}
          >
            <legend style={{ fontSize: '12px', color: theme.colors.textSecondary }}>{meta.label}</legend>
            {Object.entries(meta.fields ?? {}).map(([fieldId, fieldMeta]) => (
              <FactField
                key={fieldId}
                meta={fieldMeta}
                value={recordVal[fieldId]}
                onChange={(v) => onChange({ ...recordVal, [fieldId]: v })}
              />
            ))}
          </fieldset>
        </div>
      );
    }

    default:
      return (
        <div style={wrapStyle}>
          <label style={labelStyle}>{meta.label}</label>
          <input
            type="text"
            value={typeof value === 'string' ? value : JSON.stringify(value ?? '')}
            onChange={(e) => onChange(e.target.value)}
            style={inputStyle}
          />
        </div>
      );
  }
}
"##
    .to_string()
}
