//! Flow execution and flow history component generation.

/// Generate `FlowExecution.tsx` content.
pub(in crate::ui) fn emit_flow_execution() -> String {
    r#"// Auto-generated by tenor ui. Do not edit.
import { theme } from '../theme';
import { FlowResult } from '../api';

interface FlowExecutionProps {
  flowId: string;
  mode: 'execute' | 'simulate';
  result: FlowResult | null;
  loading: boolean;
  error: string | null;
}

export function FlowExecution({ flowId, mode, result, loading, error }: FlowExecutionProps) {
  if (loading) {
    return (
      <div style={{ color: theme.colors.textSecondary, padding: theme.spacing.md }}>
        {mode === 'simulate' ? 'Simulating' : 'Executing'} {flowId}...
      </div>
    );
  }

  if (error) {
    return (
      <div
        style={{
          backgroundColor: '#fef2f2',
          border: `1px solid ${theme.colors.error}`,
          borderRadius: theme.borderRadius.md,
          padding: theme.spacing.md,
          color: theme.colors.error,
        }}
      >
        <strong>Error:</strong> {error}
      </div>
    );
  }

  if (!result) return null;

  const isSimulation = result.simulation === true || mode === 'simulate';
  const outcomeColor =
    result.outcome === 'success' ? theme.colors.success : theme.colors.error;

  return (
    <div
      style={{
        backgroundColor: theme.colors.surface,
        border: `2px solid ${isSimulation ? theme.colors.secondary : theme.colors.border}`,
        borderRadius: theme.borderRadius.md,
        padding: theme.spacing.md,
      }}
    >
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: theme.spacing.md }}>
        <h3 style={{ margin: 0, color: theme.colors.primary }}>{result.flow_id}</h3>
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
          {isSimulation && (
            <span
              style={{
                backgroundColor: theme.colors.secondary,
                color: '#fff',
                borderRadius: theme.borderRadius.sm,
                padding: '2px 8px',
                fontSize: '12px',
                fontWeight: 600,
              }}
            >
              SIMULATION
            </span>
          )}
          <span
            style={{
              color: outcomeColor,
              fontWeight: 600,
              fontSize: '14px',
            }}
          >
            {result.outcome.toUpperCase()}
          </span>
        </div>
      </div>

      {/* State changes */}
      {result.entity_state_changes.length > 0 && (
        <div style={{ marginBottom: theme.spacing.md }}>
          <h4 style={{ fontSize: '13px', marginBottom: '6px' }}>State Changes</h4>
          <table
            style={{
              width: '100%',
              fontSize: '13px',
              borderCollapse: 'collapse',
            }}
          >
            <thead>
              <tr style={{ color: theme.colors.textSecondary }}>
                <th style={{ textAlign: 'left', paddingBottom: '4px' }}>Entity</th>
                <th style={{ textAlign: 'left', paddingBottom: '4px' }}>From</th>
                <th style={{ textAlign: 'left', paddingBottom: '4px' }}>To</th>
              </tr>
            </thead>
            <tbody>
              {result.entity_state_changes.map((change, i) => (
                <tr key={i}>
                  <td style={{ fontFamily: theme.fonts.mono }}>{change.entity_id}</td>
                  <td style={{ color: theme.colors.warning }}>{change.from_state}</td>
                  <td style={{ color: theme.colors.success }}>{change.to_state}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Steps executed */}
      {result.steps_executed.length > 0 && (
        <div style={{ marginBottom: theme.spacing.md }}>
          <h4 style={{ fontSize: '13px', marginBottom: '6px' }}>Steps Executed</h4>
          {result.steps_executed.map((step, i) => (
            <div
              key={i}
              style={{
                fontSize: '12px',
                color: theme.colors.textSecondary,
                fontFamily: theme.fonts.mono,
                marginBottom: '2px',
              }}
            >
              {step.step_id}: {step.result}
            </div>
          ))}
        </div>
      )}

      {/* Verdicts summary */}
      {result.verdicts.length > 0 && (
        <div>
          <h4 style={{ fontSize: '13px', marginBottom: '6px' }}>Verdicts</h4>
          {result.verdicts.map((v, i) => (
            <div
              key={i}
              style={{
                fontSize: '12px',
                display: 'flex',
                justifyContent: 'space-between',
                marginBottom: '2px',
              }}
            >
              <span style={{ color: theme.colors.info }}>{v.verdict_type}</span>
              <span style={{ fontFamily: theme.fonts.mono, color: theme.colors.textSecondary }}>
                {JSON.stringify(v.payload)}
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
"#
    .to_string()
}

/// Generate `FlowHistory.tsx` content.
pub(in crate::ui) fn emit_flow_history() -> String {
    r#"// Auto-generated by tenor ui. Do not edit.
import { useState, useEffect } from 'react';
import { theme } from '../theme';
import { client, FlowExecution } from '../api';
import { FLOWS, PERSONAS } from '../types';

export function FlowHistory() {
  const [history, setHistory] = useState<FlowExecution[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filterFlow, setFilterFlow] = useState('');
  const [filterPersona, setFilterPersona] = useState('');
  const [filterOutcome, setFilterOutcome] = useState('');
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  useEffect(() => {
    setLoading(true);
    client
      .getExecutionHistory()
      .then(setHistory)
      .catch((e) => setError(e instanceof Error ? e.message : String(e)))
      .finally(() => setLoading(false));
  }, []);

  const filtered = history.filter((entry) => {
    if (filterFlow && entry.flow_id !== filterFlow) return false;
    if (filterPersona && entry.persona !== filterPersona) return false;
    if (filterOutcome && entry.outcome !== filterOutcome) return false;
    return true;
  });

  const toggleExpanded = (id: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  return (
    <div style={{ padding: theme.spacing.lg }}>
      <h1 style={{ color: theme.colors.primary, marginBottom: theme.spacing.lg }}>
        Flow History
      </h1>

      {/* Filters */}
      <div style={{ display: 'flex', gap: theme.spacing.md, marginBottom: theme.spacing.md, flexWrap: 'wrap' }}>
        <select
          value={filterFlow}
          onChange={(e) => setFilterFlow(e.target.value)}
          style={{ padding: '6px 10px', borderRadius: theme.borderRadius.sm, border: `1px solid ${theme.colors.border}` }}
        >
          <option value="">All flows</option>
          {FLOWS.map((f) => (
            <option key={f.id} value={f.id}>{f.id}</option>
          ))}
        </select>

        <select
          value={filterPersona}
          onChange={(e) => setFilterPersona(e.target.value)}
          style={{ padding: '6px 10px', borderRadius: theme.borderRadius.sm, border: `1px solid ${theme.colors.border}` }}
        >
          <option value="">All personas</option>
          {PERSONAS.map((p) => (
            <option key={p} value={p}>{p}</option>
          ))}
        </select>

        <select
          value={filterOutcome}
          onChange={(e) => setFilterOutcome(e.target.value)}
          style={{ padding: '6px 10px', borderRadius: theme.borderRadius.sm, border: `1px solid ${theme.colors.border}` }}
        >
          <option value="">All outcomes</option>
          <option value="success">Success</option>
          <option value="failure">Failure</option>
        </select>
      </div>

      {loading && <div style={{ color: theme.colors.textSecondary }}>Loading history...</div>}
      {error && <div style={{ color: theme.colors.error }}>{error}</div>}

      {filtered.length === 0 && !loading && (
        <div style={{ color: theme.colors.textSecondary }}>No executions match the current filters.</div>
      )}

      {filtered.map((entry) => {
        const isExpanded = expanded.has(entry.execution_id);
        const outcomeColor =
          entry.outcome === 'success' ? theme.colors.success : theme.colors.error;
        return (
          <div
            key={entry.execution_id}
            style={{
              backgroundColor: theme.colors.surface,
              border: `1px solid ${theme.colors.border}`,
              borderRadius: theme.borderRadius.md,
              marginBottom: theme.spacing.sm,
              overflow: 'hidden',
            }}
          >
            <div
              onClick={() => toggleExpanded(entry.execution_id)}
              style={{
                padding: theme.spacing.sm,
                cursor: 'pointer',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
              }}
            >
              <div style={{ display: 'flex', gap: theme.spacing.md, alignItems: 'center' }}>
                <span style={{ fontSize: '12px' }}>{isExpanded ? '▾' : '▸'}</span>
                <span style={{ fontWeight: 600, fontSize: '13px' }}>{entry.flow_id}</span>
                <span style={{ color: theme.colors.textSecondary, fontSize: '12px' }}>
                  {entry.persona}
                </span>
              </div>
              <div style={{ display: 'flex', gap: theme.spacing.md, alignItems: 'center' }}>
                <span style={{ color: outcomeColor, fontWeight: 600, fontSize: '12px' }}>
                  {entry.outcome.toUpperCase()}
                </span>
                <span style={{ color: theme.colors.textSecondary, fontSize: '11px' }}>
                  {new Date(entry.timestamp).toLocaleString()}
                </span>
              </div>
            </div>
            {isExpanded && (
              <div
                style={{
                  padding: theme.spacing.sm,
                  borderTop: `1px solid ${theme.colors.border}`,
                  fontSize: '13px',
                }}
              >
                <div style={{ marginBottom: '4px', color: theme.colors.textSecondary, fontSize: '11px' }}>
                  ID: {entry.execution_id}
                </div>
                {entry.entity_state_changes.length > 0 && (
                  <div>
                    <strong style={{ fontSize: '12px' }}>State Changes:</strong>
                    {entry.entity_state_changes.map((change, i) => (
                      <div key={i} style={{ fontSize: '12px', paddingLeft: '8px' }}>
                        {change.entity_id}: {change.from_state} → {change.to_state}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
"#
    .to_string()
}
