//! Provenance drill-down and verdict display component generation.

/// Generate `ProvenanceDrill.tsx` content.
pub(in crate::ui) fn emit_provenance_drill() -> String {
    r##"// Auto-generated by tenor ui. Do not edit.
import { useState } from 'react';
import { theme } from '../theme';
import { Verdict } from '../api';

interface ProvenanceDrillProps {
  verdicts: Verdict[];
}

interface TreeNodeProps {
  label: string;
  color: string;
  children?: React.ReactNode;
  defaultExpanded?: boolean;
}

function TreeNode({ label, color, children, defaultExpanded = false }: TreeNodeProps) {
  const [expanded, setExpanded] = useState(defaultExpanded);

  return (
    <div style={{ marginLeft: '12px' }}>
      <div
        onClick={() => setExpanded(!expanded)}
        style={{
          cursor: children ? 'pointer' : 'default',
          color,
          fontSize: '13px',
          padding: '2px 0',
          display: 'flex',
          alignItems: 'center',
          gap: '4px',
        }}
      >
        {children && <span>{expanded ? '▾' : '▸'}</span>}
        {!children && <span style={{ display: 'inline-block', width: '12px' }} />}
        <span>{label}</span>
      </div>
      {expanded && children && (
        <div style={{ borderLeft: `2px solid ${theme.colors.border}`, marginLeft: '6px' }}>
          {children}
        </div>
      )}
    </div>
  );
}

export function ProvenanceDrill({ verdicts }: ProvenanceDrillProps) {
  if (verdicts.length === 0) {
    return <div style={{ color: theme.colors.textSecondary }}>No provenance data available.</div>;
  }

  return (
    <div
      style={{
        backgroundColor: theme.colors.surface,
        border: `1px solid ${theme.colors.border}`,
        borderRadius: theme.borderRadius.md,
        padding: theme.spacing.md,
      }}
    >
      <h3 style={{ fontSize: '14px', marginBottom: theme.spacing.sm }}>Provenance</h3>
      {verdicts.map((verdict, i) => (
        <TreeNode
          key={i}
          label={`Verdict: ${verdict.verdict_type} = ${JSON.stringify(verdict.payload)}`}
          color={theme.colors.info}
          defaultExpanded={true}
        >
          <TreeNode
            label={`Rule: ${verdict.provenance.rule_id} (stratum ${verdict.provenance.stratum})`}
            color="#7c3aed"
            defaultExpanded={false}
          >
            {verdict.provenance.facts_examined.map((factId, j) => (
              <TreeNode
                key={j}
                label={`Fact: ${factId}`}
                color={theme.colors.success}
              />
            ))}
          </TreeNode>
        </TreeNode>
      ))}
    </div>
  );
}
"##
    .to_string()
}

/// Generate `VerdictDisplay.tsx` content.
pub(in crate::ui) fn emit_verdict_display() -> String {
    r#"// Auto-generated by tenor ui. Do not edit.
import { theme } from '../theme';
import { Verdict } from '../api';
import { ProvenanceDrill } from './ProvenanceDrill';
import { useState } from 'react';

interface VerdictDisplayProps {
  verdicts: Verdict[];
}

export function VerdictDisplay({ verdicts }: VerdictDisplayProps) {
  const [selected, setSelected] = useState<Verdict | null>(null);

  if (verdicts.length === 0) {
    return <div style={{ color: theme.colors.textSecondary }}>No verdicts to display.</div>;
  }

  // Group verdicts by stratum
  const byStratum = new Map<number, Verdict[]>();
  for (const v of verdicts) {
    const s = v.provenance.stratum;
    const existing = byStratum.get(s) ?? [];
    byStratum.set(s, [...existing, v]);
  }

  const strata = Array.from(byStratum.keys()).sort((a, b) => a - b);

  return (
    <div>
      {strata.map((stratum) => (
        <div key={stratum} style={{ marginBottom: theme.spacing.md }}>
          <h4 style={{ fontSize: '13px', color: theme.colors.textSecondary, marginBottom: '6px' }}>
            Stratum {stratum}
          </h4>
          {(byStratum.get(stratum) ?? []).map((verdict, i) => {
            const isTruthy =
              verdict.payload === true ||
              (typeof verdict.payload === 'number' && verdict.payload !== 0) ||
              (typeof verdict.payload === 'string' && verdict.payload !== '');
            return (
              <div
                key={i}
                onClick={() => setSelected(selected === verdict ? null : verdict)}
                style={{
                  backgroundColor: theme.colors.surface,
                  border: `1px solid ${theme.colors.border}`,
                  borderRadius: theme.borderRadius.sm,
                  padding: '6px 10px',
                  marginBottom: '4px',
                  cursor: 'pointer',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span style={{ fontSize: '16px' }}>{isTruthy ? '✓' : '✗'}</span>
                  <span style={{ fontSize: '13px', color: theme.colors.info }}>
                    {verdict.verdict_type}
                  </span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span
                    style={{
                      fontFamily: theme.fonts.mono,
                      fontSize: '12px',
                      color: theme.colors.textSecondary,
                    }}
                  >
                    {JSON.stringify(verdict.payload)}
                  </span>
                  <span style={{ fontSize: '11px', color: theme.colors.textSecondary }}>
                    via {verdict.provenance.rule_id}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      ))}

      {selected && (
        <div style={{ marginTop: theme.spacing.md }}>
          <ProvenanceDrill verdicts={[selected]} />
        </div>
      )}
    </div>
  );
}
"#
    .to_string()
}
